version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: network_app
    volumes:
      - ./:/usr/src/app:ro
    ports:
      - "8000:8000"

    env_file:
      - ./networking/.env

  postgres:
    image: postgres
    env_file:
      - ./networking/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  volumes:
    postgres-db:
